# Meteo station Device
{
    "id":{
         "prefix":"urn:ngsi-ld:Device:unipg:",
         "mapping":"id",
        },
    "name": "Weather Station",
    "type": "Device",
    "deviceCategory": ["sensor"],
    "controlledProperty": ["temperature", "umidity", "solarRadiation", "windSpeed", "evotranspiration", "precipitation"]
}